apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: Towerwatch  
  labels:
    app: frontend
spec:
  replicas: 3  owerwatch
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/<REPOSITORY_NAME>:<GITHUB_SHA>
        imagePullPolicy: Always
        ports:
        - containerPort: 80  
   #     env:
   #     - name: ENV_VAR_1  
   #       value: "value1"
   #     - name: ENV_VAR_2
   #       value: "value2"
