apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
  namespace: Towerwatch  
  labels:
    app: frontend
spec:
  replicas: 3  
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      containers:
      - name: heimdall
        image: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/<REPOSITORY_NAME>:<GITHUB_SHA>
        imagePullPolicy: Always
        ports:
        - containerPort: 7000 
   #     env:
   #     - name: ENV_VAR_1  
   #       value: "value1"
   #     - name: ENV_VAR_2
   #       value: "value2"
