apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
  namespace: Towerwatch  
  labels:
    app: heimdall
spec:
  replicas: 2  
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      containers:
      - name: heimdall
        image: 009925156537.dkr.ecr.eu-west-1.amazonaws.com/towerwatch:heimdall-8d32db8
        imagePullPolicy: Always
        ports:
        - containerPort: 7000 