apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-ingestor
  namespace: towerwatch  
  labels:
    app: influxdb-ingestor
spec:
  replicas: 2  
  template:
    metadata:
      labels:
        app: influxdb-ingestor
    spec:
      containers:
      - name: influxdb-ingestor
        image: 009925156537.dkr.ecr.eu-west-1.amazonaws.com/towerwatch:influxdb_ingestor-810b502
        imagePullPolicy: Always
        ports:
        - containerPort: 9000 