apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-ingestor
  namespace: towerwatch  
  labels:
    app: influxdb-ingestor
spec:
  replicas: 2
  selector:  
    matchLabels:
      app: influxdb-ingestor
  template:
    metadata:
      labels:
        app: influxdb-ingestor
    spec:
      containers:
      - name: influxdb-ingestor
        image: 009925156537.dkr.ecr.eu-west-1.amazonaws.com/towerwatch-influxdb-ingestor:influxdb_ingestor-806fa2d
        imagePullPolicy: Always
        ports:
        - containerPort: 9000 
      imagePullSecrets:
      - name: ecr-docker-secret


---

apiVersion: v1
kind: Service
metadata:
  name: influxdb-ingestor
  namespace: towerwatch
  labels:
    app: influxdb-ingestor
spec:
  selector:
    app: influxdb-ingestor # Matches the Pod labels
  ports:
    - protocol: TCP
      port: 9000         # The port exposed by the Service
      targetPort: 9000 # The containerPort in the Pod
  type: ClusterIP   