apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-ingestor
  namespace: towerwatch  
  labels:
    app: influxdb-ingestor
spec:
  replicas: 2
  selector:  
    matchLabels:
      app: influxdb-ingestor
  template:
    metadata:
      labels:
        app: influxdb-ingestor
    spec:
      containers:
      - name: influxdb-ingestor
        image: 009925156537.dkr.ecr.eu-west-1.amazonaws.com/towerwatch-influxdb-ingestor:influxdb_ingestor-707aca7
        imagePullPolicy: Always
        ports:
        - containerPort: 9000 
        env:
        - name: VAULT_ADDR
          valueFrom:
            secretKeyRef:
              name: vault-config
              key: VAULT_ADDR
        - name: VAULT_USERNAME
          valueFrom:
            secretKeyRef:
              name: vault-config
              key: VAULT_USERNAME
        - name: VAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vault-config
              key: VAULT_PASSWORD
        - name: VAULT_USER_SECRETS_PATH
          valueFrom:
            secretKeyRef:
              name: vault-config
              key: VAULT_USER_SECRETS_PATH
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: vault-config
              key: AWS_ACCESS_KEY_ID
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: vault-config
              key: AWS_REGION
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: vault-config
              key: AWS_SECRET_ACCESS_KEY

      imagePullSecrets:
      - name: docker-ecr-secret


---

apiVersion: v1
kind: Service
metadata:
  name: influxdb-ingestor
  namespace: towerwatch
  labels:
    app: influxdb-ingestor
spec:
  selector:
    app: influxdb-ingestor # Matches the Pod labels
  ports:
    - protocol: TCP
      port: 9000         # The port exposed by the Service
      targetPort: 9000 # The containerPort in the Pod
  type: ClusterIP   
