apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvis
  namespace: towerwatch
  labels:
    app: jarvis
spec:
  replicas: 2
  selector:  
    matchLabels:
      app: jarvis
  template:
    metadata:
      labels:
        app: jarvis  
    spec:
      containers:
      - name: jarvis
        image: 009925156537.dkr.ecr.eu-west-1.amazonaws.com/towerwatch:jarvis-541714b
        imagePullPolicy: Always
        ports:
        - containerPort: 6000
