apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvis
  namespace: towerwatch
  labels:
    app: jarvis
spec:
  replicas: 2
  selector:  
    matchLabels:
      app: jarvis
  template:
    metadata:
      labels:
        app: jarvis  
    spec:
      containers:
      - name: jarvis
        image: 009925156537.dkr.ecr.eu-west-1.amazonaws.com/towerwatch-jarvis:jarvis-3a42e97
        imagePullPolicy: Always
        ports:
        - containerPort: 6000
        env:
        - name: VAULT_ADDR
          valueFrom:
            secretKeyRef:
              name: vault-config
              key: VAULT_ADDR
        - name: VAULT_USERNAME
          valueFrom:
            secretKeyRef:
              name: vault-config
              key: VAULT_USERNAME
        - name: VAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vault-config
              key: VAULT_PASSWORD
        - name: VAULT_USER_SECRETS_PATH
          valueFrom:
            secretKeyRef:
              name: vault-config
              key: VAULT_USER_SECRETS_PATH
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: vault-config
              key: AWS_ACCESS_KEY_ID
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: vault-config
              key: AWS_REGION
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: vault-config
              key: AWS_SECRET_ACCESS_KEY

      imagePullSecrets:
      - name: docker-ecr-secret


---

apiVersion: v1
kind: Service
metadata:
  name: jarvis  
  namespace: towerwatch
  labels:
    app: jarvis  
spec:
  selector:
    app: jarvis   # Matches the Pod labels
  ports:
    - protocol: TCP
      port: 6000         # The port exposed by the Service
      targetPort: 6000 # The containerPort in the Pod
  type: ClusterIP   
