apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
  namespace: Towerwatch  
  labels:
    app: mqtt
spec:
  replicas: 2  
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      containers:
      - name: mqtt
        image: 009925156537.dkr.ecr.eu-west-1.amazonaws.com/towerwatch:mqtt-51647e2
        imagePullPolicy: Always
        ports:
        - containerPort: 3333 