apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
  namespace: towerwatch  
  labels:
    app: mqtt
spec:
  replicas: 2
  selector:  
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt 

    spec:
      containers:
      - name: mqtt
        image: 009925156537.dkr.ecr.eu-west-1.amazonaws.com/towerwatch-mqtt:mqtt-806fa2d
        imagePullPolicy: Always
        ports:
        - containerPort: 3333 
      imagePullSecrets:
      - name: ecr-docker-secret


---

apiVersion: v1
kind: Service
metadata:
  name: mqtt  
  namespace: towerwatch
  labels:
    app: mqtt 
spec:
  selector:
    app: mqtt   # Matches the Pod labels
  ports:
    - protocol: TCP
      port: 3333         # The port exposed by the Service
      targetPort: 3333 # The containerPort in the Pod
  type: ClusterIP 