apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
  namespace: Towerwatch  
  labels:
    app: mqtt
spec:
  replicas: 2  
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      containers:
      - name: mqtt
        image: <IMAGE_URI>
        imagePullPolicy: Always
        ports:
        - containerPort: 3333 