apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
  namespace: towerwatch
  labels:
    app: mqtt
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "cicd-role"
    vault.hashicorp.com/agent-inject-secret-sundarsecrets: "secret/data/towerwatchsecrets/sundarsecrets"
    vault.hashicorp.com/agent-inject-secret-commonsecrets: "secret/data/towerwatchsecrets/commonsecrets"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      serviceAccountName: vault
      containers:
      - name: mqtt
        image: 009925156537.dkr.ecr.eu-west-1.amazonaws.com/towerwatch-mqtt:mqtt-ff8e05e
        imagePullPolicy: Always
        ports:
        - containerPort: 3333
      imagePullSecrets:
      - name: docker-ecr-secret
