apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-ingestor
  namespace: towerwatch  
  labels:
    app: mysql-ingestor
spec:
  replicas: 2  
  template:
    metadata:
      labels:
        app: mysql-ingestor
    spec:
      containers:
      - name: mysql-ingestor
        image: 009925156537.dkr.ecr.eu-west-1.amazonaws.com/towerwatch:mysql_ingestor-f1e26df
        imagePullPolicy: Always
        ports:
        - containerPort: 8000 
      imagePullSecrets:
      - name: ecr-pull-secret


---

apiVersion: v1
kind: Service
metadata:
  name: mysql-ingestor  
  namespace: towerwatch
  labels:
    app: mysql-ingestor 
spec:
  selector:
    app: mysql-ingestor   # Matches the Pod labels
  ports:
    - protocol: TCP
      port: 8000         # The port exposed by the Service
      targetPort: 8000 # The containerPort in the Pod
  type: ClusterIP 