apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment.yml
  namespace: Towerwatch  
  labels:
    app: mysql-deployment.yml
spec:
  replicas: 2  
  template:
    metadata:
      labels:
        app: mysql-deployment.yml
    spec:
      containers:
      - name: mysql-deployment.yml
        image: 009925156537.dkr.ecr.eu-west-1.amazonaws.com/towerwatch:mysql_ingestor-f1e26df
        imagePullPolicy: Always
        ports:
        - containerPort: 8000 