apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-ingestor
  namespace: towerwatch  
  labels:
    app: mysql-ingestor
spec:
  replicas: 2
  selector:  
    matchLabels:
      app: mysql-ingestor
  template:
    metadata:
      labels:
        app: mysql-ingestor 
    spec:
      containers:
      - name: mysql-ingestor
        image: 009925156537.dkr.ecr.eu-west-1.amazonaws.com/towerwatch-mysql-ingestor:mysql_ingestor-222d676
        imagePullPolicy: Always
        env:
        - name: VAULT_ADDR
          valueFrom:
            secretKeyRef:
              name: vault-config
              key: VAULT_ADDR
        - name: VAULT_USERNAME
          valueFrom:
            secretKeyRef:
              name: vault-config
              key: VAULT_USERNAME
        - name: VAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vault-config
              key: VAULT_PASSWORD
        - name: VAULT_USER_SECRETS_PATH
          valueFrom:
            secretKeyRef:
              name: vault-config
              key: VAULT_USER_SECRETS_PATH

        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: vault-config
              key: AWS_ACCESS_KEY_ID
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: vault-config
              key: AWS_REGION
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: vault-config
              key: AWS_SECRET_ACCESS_KEY

        ports:
        - containerPort: 8000 
      imagePullSecrets:
      - name: docker-ecr-secret


---

apiVersion: v1
kind: Service
metadata:
  name: mysql-ingestor  
  namespace: towerwatch
  labels:
    app: mysql-ingestor 
spec:
  selector:
    app: mysql-ingestor   # Matches the Pod labels
  ports:
    - protocol: TCP
      port: 8000         # The port exposed by the Service
      targetPort: 8000 # The containerPort in the Pod
  type: ClusterIP 
