name: Towerwatch CI/CD Pipeline
    
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Check out the code
        uses: actions/checkout@v3

      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  

      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start mysql_ingestor
        run: |
         python3 mysql_ingestor/run.py &
         sleep 10  

    # Run all other modules in parallel
      - name: Run other modules concurrently
        run: |
         python3 mqtt/mqtt_sub.py &
         python3 jarvis/etl_handler.py &
         python3 heimdall/heimdall_handler.py &
         wait     

  deploy:
    runs-on: ubuntu-latest
    needs: build  

    steps:
      
      - name: Check out the code
        uses: actions/checkout@v3

      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

   #   - name: Deploy
    #    run: |
    #      echo "Deploying the application..."  # Replace with your actual deployment command
