name: CI/CD Pipeline for Heimdall

on:
  push:
    paths:
      - './heimdall/**'      
  workflow_dispatch: 

jobs:
  lint-and-test:
    name: Lint, Security Check, and Test Python Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r dev-requirements.txt

      - name: Install Dependencies
        working-directory: ./heimdall
        run: pip install -r requirements.txt

      - name: Run Pylint
        working-directory: ./heimdall
        run: pylint **/*.py || true

      - name: Install Vulture
        working-directory: ./heimdall
        run: pip install vulture

      - name: Run Vulture
        run: vulture . --min-confidence 80 || true

      - name: Run Bandit
        working-directory: ./heimdall
        run: bandit -r . || true

      - name: Run Unittests
        working-directory: ./heimdall
        run: python -m unittest discover || true

  build-push-and-deploy:
    name: Build, Push Docker Image, and Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: lint-and-test
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Login to Harbor Registry
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | docker login ${{ secrets.HARBOR_URL }} -u ${{ secrets.HARBOR_USERNAME }} --password-stdin

      - name: Build Docker Image
        working-directory: ./heimdall
        run: |
          IMAGE_TAG=${GITHUB_SHA:0:7}
          docker build -t ${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT }}/heimdall:heimdall-$IMAGE_TAG .

      - name: Push Docker Image to Harbor
        run: |
          IMAGE_TAG=${GITHUB_SHA:0:7}
          docker push ${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT }}/heimdall:heimdall-$IMAGE_TAG

      - name: Update HEIMDALL Deployment file
        working-directory: ./manifests
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "https://$GITHUB_TOKEN@github.com" > ~/.git-credentials
          git config --global credential.helper store
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          IMAGE_TAG=${GITHUB_SHA:0:7}
          IMAGE_URI=${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT }}/heimdall:heimdall-$IMAGE_TAG
          sed -i "s|image: .*|image: $IMAGE_URI|g" heimdall-deployment.yml
          
          git add heimdall-deployment.yml
          git commit -m "Update deployment image to $IMAGE_URI"
          git pull --rebase origin development
          git push https://$GITHUB_TOKEN@github.com/${{ github.repository }}.git HEAD:development

      - name: Cleanup Git Credentials
        if: always()
        run: |
          rm -f ~/.git-credentials
