name: CI/CD Pipeline for Heimdall

on:
  push:
    paths:
      - './heimdall/**'      
  workflow_dispatch: 

jobs:
  lint-and-test:
    name: Lint, Security Check, and Test Python Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r dev-requirements.txt


      - name: Install Dependencies
        working-directory: ./heimdall
        run: pip install -r requirements.txt

      - name: Run Pylint
        working-directory: ./heimdall
        run: pylint **/*.py || true

      - name: Install Vulture
        working-directory: ./heimdall
        run: pip install vulture

      - name: Run Vulture
        run: vulture . --min-confidence 80 || true # Adjust confidence level as needed
 
   #   - name: Upload Vulture Report
   #     if: always()
   #     run: |
   #      vulture . > vulture_report.txt
   #      artifacts:
   #      name: vulture-report
   #      path: vulture_report.txt

      - name: Run Bandit
        working-directory: ./heimdall
        run: bandit -r . || true

      - name: Run Unittests
        working-directory: ./heimdall
        run: python -m unittest discover || true

  build-push-and-deploy:
    name: Build, Push Docker Image, and Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: lint-and-test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

        
      - name: Build Docker Image
        working-directory: ./heimdall
        run: |
          IMAGE_TAG=${GITHUB_SHA:0:7}
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.HEIMDALL }}:heimdall-$IMAGE_TAG .

      - name: Push Docker Image to ECR
        run: |
          IMAGE_TAG=${GITHUB_SHA:0:7}
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.HEIMDALL }}:heimdall-$IMAGE_TAG

      - name: Update HEIMDALL Deployment file
        working-directory: ./manifests
        run: |
          IMAGE_TAG=${GITHUB_SHA:0:7}
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.HEIMDALL }}:heimdall-$IMAGE_TAG

          sed -i "s|image: .*|image: $IMAGE_URI|g" heimdall-deployment.yml
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git pull
          git add heimdall-deployment.yml
          git commit -m "Update deployment image to $IMAGE_URI"

      - name: Push Changes
        run: |
          git push origin ${{ github.ref }}

  deploy-to-ec2:
    name: Deploy Docker Image to EC2 (Manual Confirmation Required)
    runs-on: ubuntu-latest
    needs: build-push-and-deploy  # Depends on the build-push-and-deploy job
    if: github.event_name == 'workflow_dispatch'  # Only trigger on manual dispatch

    steps:
      - name: Approval Required
        uses: hmarr/auto-approve-action@v2
        with:
          comment: "Manual approval required to proceed with deployment."
      
      - name: Wait for Manual Approval
        run: |
          echo "Waiting for manual approval..."
          while ! [ -f /tmp/approved ]; do sleep 10; done

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.SUNDAR_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SUNDAR_SECRET_KEY }}
          aws-region: ${{ secrets.SUNDAR_AWS_REGION }}

      - name: SSH into EC2 Instance and Deploy
        env:
          IMAGE_URI: ${{ secrets.SUNDAR_AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.SUNDAR_AWS_REGION }}.amazonaws.com/${{ secrets.HEIMDALL }}:heimdall-${{ github.sha }}
          ENV_VAR1: ${{ secrets.VAULT_ADDR }}
          ENV_VAR2: ${{ secrets.VAULT_USERNAME }}
          ENV_VAR3: ${{secrets.VAULT_PASSWORD}}
          ENV_VAR4: ${{secrets.VAULT_USER_SECRETS_PATH}}
        run: |
          ssh -o "StrictHostKeyChecking=no" -i ${{ secrets.SUNDAR_EC2_SSH_KEY }} ubuntu@${{ secrets.SUNDAR_EC2_PUBLIC_IP }} << 'EOF'
            docker pull $IMAGE_URI
            docker run -d --name heimdall-container \
              -e ENV_VAR1=$VAULT_ADDR \
              -e ENV_VAR2=$VAULT_USERNAME \
              -e ENV_VAR3=$VAULT_PASSWORD \
              -e ENV_VAR4=$VAULT_USER_SECRETS_PATH \
              $IMAGE_URI
          EOF