name: CI/CD Pipeline for Python Backend

on:
  push:
    paths:
      - './jarvis/**'
  workflow_dispatch:

jobs:
  lint-and-test:
    name: Lint, Security Check, and Test Python Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r dev-requirements.txt


      - name: Install Dependencies
        working-directory: ./jarvis
        run: pip install -r requirements.txt

      - name: Run Pylint
        working-directory: ./jarvis
        run: pylint **/*.py || true

      - name: Install Vulture
        working-directory: ./jarvis
        run: pip install vulture

      - name: Run Vulture
        run: vulture . --min-confidence 80 || true # Adjust confidence level as needed
 
   #   - name: Upload Vulture Report
   #     if: always()
   #     run: |
   #      vulture . > vulture_report.txt
   #      artifacts:
   #      name: vulture-report
   #      path: vulture_report.txt

      - name: Run Bandit
        working-directory: ./jarvis
        run: bandit -r . || true

      - name: Run Unittests
        working-directory: ./jarvis
        run: python -m unittest discover || true

  build-push-and-deploy:
    name: Build, Push Docker Image, and Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: lint-and-test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image
        working-directory: ./jarvis
        run: |
          IMAGE_TAG=${GITHUB_SHA:0:7}
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.REPOSITORY_NAME }}:jarvis-$IMAGE_TAG .

      - name: Push Docker Image to ECR
        run: |
          IMAGE_TAG=${GITHUB_SHA:0:7}
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.REPOSITORY_NAME }}:jarvis-$IMAGE_TAG

      - name: Update Kubernetes Deployment
        env:
          IMAGE_TAG: ${GITHUB_SHA:0:7}
          IMAGE_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.REPOSITORY_NAME }}:jarvis-$IMAGE_TAG
        run: |
    
          sed -i "s|<AWS_ACCOUNT_ID>|${{ secrets.AWS_ACCOUNT_ID }}|g" deployment.yaml
          sed -i "s|<AWS_REGION>|${{ secrets.AWS_REGION }}|g" deployment.yaml
          sed -i "s|<REPOSITORY_NAME>|${{ secrets.REPOSITORY_NAME }}|g" deployment.yaml
          sed -i "s|<GITHUB_SHA>|$IMAGE_TAG|g" deployment.yaml

    
          kubectl apply -f deployment.yaml
